namespace OwlStock.Infrastructure.Common.EmailTemplates.Account
{
    public static class AccountEmailTemplates
    {
        public static string CreateAccountTemplate(string password)
        {
            return $"<!doctypehtml><html lang=en><meta charset=UTF-8><meta content=\"width=device-width,initial-scale=1\"name=viewport><title>Създадохме вашия профил</title><body style=font-family:Verdana,Geneva,Tahoma,sans-serif><div id=container style=width:100%><div style=\"width:50%;margin:0 auto\"class=container-main><div id=container-main-header><div id=container-main-header-logo style=width:100%;text-align:center><img src=https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic.png style=width:50%></div></div><div id=container-main-title style=width:100%;margin-top:100px><h1 style=text-align:center;color:#000>Създадохме Вашия профил</h1></div><div id=container-main-text style=margin-top:80px><p style=font-size:1.5rem;color:#000>Създадохме личен профил за Вас и сега можете да се възползвате от всички функционалости, налични на нашия сайт.<p style=font-size:1.5rem;color:#000>Благодарим Ви, че изплозвате нашите услуги!<p style=font-size:1.3rem;margin-top:50px;font-weight:700;color:#000>Вашата парола: <span style=text-decoration:none;color:#eaa636>{password}</span></div><div id=container-main-footer style=margin-top:100px><div id=container-main-footer-text style=\"margin:0 auto;background-color:#eaa636;padding:5px 0\"><h4 style=text-align:center;color:#000><a href=http://www.flash-studio.co style=text-decoration:none;color:#000>PHOTONIC</a> © {DateTime.Now.Year}</h4></div></div></div></div>";

        }

        public static string CreateConfirmedAccountTemplate()
        {
            return "<!doctypehtml><style>@media only screen and (max-width:600px){.container{width:100%!important}.responsive-img{width:100%!important;height:auto!important}}</style><body style=margin:0;padding:0><table border=0 cellpadding=0 cellspacing=0 width=100%><tr><td style=padding:20px align=center bgcolor=#f0f0f0><table border=0 cellpadding=0 cellspacing=0 width=600 class=container style=background-color:#fff><tr><td style=padding:20px;text-align:center><img src=https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic.png style='display: block; padding:50px 0;width:60%;margin:0 auto;text-align:center;'><h1 style=color:#333;font-family:Arial,sans-serif>Създадохме Вашия профил</h1><h2 style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Благодарим Ви, че използват нашите услуги!</h2><h2>Можете да следите кадрите от фотосесиите си тук:</a></b></h2><h4><a href='http://flash-studio.co/PhotoShoot/MyPhotoShoots'>Моите фотосеии</a></h4><div class=footer-wrap style=margin-top:60px;width:100%;background:#585858;color:#fff;padding:1px 0><footer style=text-align:center><h4>PHOTONIC ©" + DateTime.Now.Year + "</h4></footer></div><div class=footer-links-wrap style=width:100%;text-align:center;margin-top:10px><a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>Photonic</a> <a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>@photonic.bg</a></div></table></table>";

        }

        public static string ConfirmAccountTemplate(string confirmationLink)
        {
            return "<!doctypehtml><style>@media only screen and (max-width:600px){.container{width:100%!important}.responsive-img{width:100%!important;height:auto!important}}</style><body style=margin:0;padding:0><table border=0 cellpadding=0 cellspacing=0 width=100%><tr><td style=padding:20px align=center bgcolor=#f0f0f0><table border=0 cellpadding=0 cellspacing=0 width=600 class=container style=background-color:#fff><tr><td style=padding:20px;text-align:center><img src=https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic.png style='display: block; padding:50px 0;width:60%;margin:0 auto;text-align:center;'><h1 style=color:#333;font-family:Arial,sans-serif>Създадохме Вашия профил</h1><h2 style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Благодарим Ви, че използват нашите услуги!</h2><p style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Потвърдете акаунта си на този линк:</p><p style='margin-top:20px'>" + confirmationLink + "</p>" + "<div class=footer-wrap style=margin-top:60px;width:100%;background:#585858;color:#fff;padding:1px 0><footer style=text-align:center><h4>PHOTONIC ©" + DateTime.Now.Year + "</h4></footer></div><div class=footer-links-wrap style=width:100%;text-align:center;margin-top:10px><a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>Photonic</a> <a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>@photonic.bg</a></div></table></table>";

        }

        public static string ResetPasswordTemplate(string callbackURL)
        {
            return "<!doctypehtml><style>@media only screen and (max-width:600px){.container{width:100%!important}.responsive-img{width:100%!important;height:auto!important}}</style><body style=margin:0;padding:0><table border=0 cellpadding=0 cellspacing=0 width=100%><tr><td style=padding:20px align=center bgcolor=#f0f0f0><table border=0 cellpadding=0 cellspacing=0 width=600 class=container style=background-color:#fff><tr><td style=padding:20px;text-align:center><img src=https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic.png style='display: block; padding:50px 0;width:60%;margin:0 auto;text-align:center;'><h1 style=color:#333;font-family:Arial,sans-serif>Възстановяване на парола</h1><h2 style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Клинкенте върху линка по-долу, за да възстанвите паролата си</h2><p style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>" + callbackURL + "</p>" + "<div class=footer-wrap style=margin-top:60px;width:100%;background:#585858;color:#fff;padding:1px 0><footer style=text-align:center><h4>PHOTONIC © " + DateTime.Now.Year + "</h4></footer></div><div class=footer-links-wrap style=width:100%;text-align:center;margin-top:10px><a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>Photonic</a> <a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>@photonic.bg</a></div></table></table>";

        }
    }    
}
