namespace OwlStock.Infrastructure.Common.EmailTemplates.Account
{
    public static class AccountEmailTemplates
    {
        public static string CreateAccountTemplate(string email, string password)
        {
            //https://i.ibb.co/Zg5pTVZ/email-check.png
            return "<!doctypehtml><style>@media only screen and (max-width:600px){.container{width:100%!important}.responsive-img{width:100%!important;height:auto!important}}</style><body style=margin:0;padding:0><table border=0 cellpadding=0 cellspacing=0 width=100%><tr><td style=padding:20px align=center bgcolor=#f0f0f0><table border=0 cellpadding=0 cellspacing=0 width=600 class=container style=background-color:#fff><tr><td style=padding:20px;text-align:center><img src=https://i.ibb.co/Zg5pTVZ/email-check.png style=display: block; background: rgba(55, 128, 73, .2); color:#378049;width:20%;margin:0 auto;padding:10px;text-align:center;border-radius:10px><h1 style=color:#333;font-family:Arial,sans-serif>Създадохме Вашия профил</h1><h2 style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Благодарим Ви, че използват нашите услуги!</h2><p style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Паролата за Вашия профил е: </p>" + $"<span style=display:inline-block;padding:10px 20px;color:#fff;background-color:#007bff;text-decoration:none;font-family:Arial,sans-serif;font-size:14px;border-radius:5px><b>{password}</b></span>" + "Можете да следите кадрите от фотосесията тук</a></b><div class=footer-wrap style=margin-top:60px;width:100%;background:#585858;color:#fff;padding:1px 0><footer style=text-align:center><h4>DREAMPIX © 2024</h4></footer></div><div class=footer-links-wrap style=width:100%;text-align:center;margin-top:10px><a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>Photon.bg</a> <a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>@dreampix</a></div></table></table>";

        }

        public static string ConfirmAccountTemplate(string confirmationLink)
        {
            //https://i.ibb.co/Zg5pTVZ/email-check.png
            return "<!doctypehtml><style>@media only screen and (max-width:600px){.container{width:100%!important}.responsive-img{width:100%!important;height:auto!important}}</style><body style=margin:0;padding:0><table border=0 cellpadding=0 cellspacing=0 width=100%><tr><td style=padding:20px align=center bgcolor=#f0f0f0><table border=0 cellpadding=0 cellspacing=0 width=600 class=container style=background-color:#fff><tr><td style=padding:20px;text-align:center><img src=https://i.ibb.co/Zg5pTVZ/email-check.png style=display: block; background: rgba(55, 128, 73, .2); color:#378049;width:20%;margin:0 auto;padding:10px;text-align:center;border-radius:10px><h1 style=color:#333;font-family:Arial,sans-serif>Създадохме Вашия профил</h1><h2 style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Благодарим Ви, че използват нашите услуги!</h2><p style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Потвърдете акаунта си на този линк: " + confirmationLink + "</p>" + "<div class=footer-wrap style=margin-top:60px;width:100%;background:#585858;color:#fff;padding:1px 0><footer style=text-align:center><h4>DREAMPIX © 2024</h4></footer></div><div class=footer-links-wrap style=width:100%;text-align:center;margin-top:10px><a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>Photon.bg</a> <a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>@dreampix</a></div></table></table>";

        }

        public static string ResetPasswordTemplate(string callbackURL)
        {
            //https://i.ibb.co/Zg5pTVZ/email-check.png
            return "<!doctypehtml><style>@media only screen and (max-width:600px){.container{width:100%!important}.responsive-img{width:100%!important;height:auto!important}}</style><body style=margin:0;padding:0><table border=0 cellpadding=0 cellspacing=0 width=100%><tr><td style=padding:20px align=center bgcolor=#f0f0f0><table border=0 cellpadding=0 cellspacing=0 width=600 class=container style=background-color:#fff><tr><td style=padding:20px;text-align:center><img src=https://i.ibb.co/Zg5pTVZ/email-check.png style=display: block; background: rgba(55, 128, 73, .2); color:#378049;width:20%;margin:0 auto;padding:10px;text-align:center;border-radius:10px><h1 style=color:#333;font-family:Arial,sans-serif>Създадохме Вашия профил</h1><h2 style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Благодарим Ви, че използват нашите услуги!</h2><p style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Последвайте този линк, за да възстановите паролата си: " + callbackURL + "</p>" + "<div class=footer-wrap style=margin-top:60px;width:100%;background:#585858;color:#fff;padding:1px 0><footer style=text-align:center><h4>DREAMPIX © 2024</h4></footer></div><div class=footer-links-wrap style=width:100%;text-align:center;margin-top:10px><a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>Photon.bg</a> <a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>@dreampix</a></div></table></table>";

        }
    }    
}
