using OwlStock.Domain.Enumerations;

namespace OwlStock.Infrastructure.Common.EmailTemplates.PhotoShoot
{
    public static class PhotoShootEmailTemplates
    {
        public static string CreatePhotoShootTemplate(DateTime date, PhotoShootType photoshootType, Guid photoshootId)
        {
            return $"<!doctypehtml><html lang=en><meta charset=UTF-8><meta content=\"width=device-width,initial-scale=1\"name=viewport><title>Резервацията беше направена успешно!</title><body style=font-family:Verdana,Geneva,Tahoma,sans-serif><div id=container style=width:100%><div style=\"width:50%;margin:0 auto\"class=container-main><div id=container-main-header><div id=container-main-header-logo style=width:100%;text-align:center><img src=https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic_UPPER_dark.png style=width:50%></div></div><div id=container-main-title style=\"width:100%;margin:60px 0\"><h1 style=text-align:center;color:#000>Фотосесията е резервирана успешно <span style=color:#eaa636>успешно</span>!</h1></div><hr><div id=container-main-table-details style=width:100%;font-size:1.3rem><table style=\"width:70%;margin:60px 0\"><tr><td><b>Фотосесия</b><td>{photoshootType}<tr><td style=text-align:left><b>Дата</b><td style=text-align:left>{date}</table></div><hr><div id=container-main-text style=margin-top:50px><p style=font-size:1.2rem>Резервацията ще бъде прегледана и ще получите обаждане от нас в най-скоро време. Повече информация може да откриете <a href=http://www.flash-studio.co/Photoshoot/PhotoshootById/{photoshootId} style=text-decoration:none;color:#eaa636><b>тук</b></a>.<p style=font-size:1.4rem;margin-top:50px;color:#000>Благодарим Ви, че изплозвате нашите услуги!<p style=font-size:1.4rem;color:#000;margin-top:50px>Поздрави,<p style=font-size:1.4rem;color:#000>Екипът на PHOTONIC</div><div id=container-main-footer style=margin-top:100px><div id=container-main-footer-text style=\"margin:0 auto;background-color:#eaa636;padding:5px 0\"><h4 style=text-align:center;color:#000><a href=http://www.flash-studio.co style=text-decoration:none;color:#000>PHOTONIC</a> © {DateTime.Now.Year}</h4></div></div></div></div>";
        }

        public static string CreatePhotoShootTemplateDreampix(DateTime date, PhotoShootType photoshootType)
        {
            return $"<div class=\"container\"> <div class=\"content\"> <h2 class=\"username\">Здравей,</h2> <br> <h1 class=\"text\">Направена е нова рервация.</i></h1> <hr> <div class=\"details\"> <table> <tbody> <tr> <td>Date:</td> <td><i>{date.ToShortDateString()}</i></td> </tr> <tr> <td>Type:</td> <td><i>{photoshootType}</i></td> </tr> </tbody> </table> </div> <hr> <div class=\"greetings\"</div> <hr> <div class=\"footer\"> <h1>OwlStock</h1> <br> <h4>2023</h4> </div> </div> </div> <style> *{{margin: 0;padding: 5px 8px;}}hr{{margin: 10px 10px;padding: 0;}}.container{{font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;width: 100%;text-align: center;}}.container .content{{width: 100%;margin: 0 auto;padding: 20px 0;background-color: #EBEAE1;}}.container .content .details table{{margin: 0 auto;}}.container .content .greetings h2{{margin-top: 20px;}}</style> ";
        }

        public static string UpdatePhotoShootTemplate(Guid photoshootId)
        {
            return $"<!doctypehtml><html lang=en><meta charset=UTF-8><meta content=\"width=device-width,initial-scale=1\"name=viewport><title>Страхотни новини!</title><body style=font-family:Verdana,Geneva,Tahoma,sans-serif><div id=container style=width:100%><div style=\"width:50%;margin:0 auto\"class=container-main><div id=container-main-header><div id=container-main-header-logo style=width:100%;text-align:center><img src=https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic_UPPER_dark.png style=width:50%></div></div><div id=container-main-title style=\"width:100%;margin:60px 0\"><h1 style=text-align:center;color:#000>Снимките от Вашата фотосесия са <span style=color:#eaa636>готови</span>!</h1></div><div id=container-main-text style=margin-top:50px><p style=font-size:1.2rem>Всички снимки от Вашата фотосесия са налични в профила Ви. Може да ги прегледате или изтеглите от Вашата лична галерия.<p style=margin-top:30px><a href=http://www.flash-studio.co/Photoshoot/PhotoshootById/{photoshootId} style=\"background:#eaa636;padding:10px 30px;text-decoration:none;color:#000\"><b>Моята галерия</b></a><p style=font-size:1.4rem;margin-top:50px;color:#000>Благодарим Ви, че изплозвате нашите услуги!<p style=font-size:1.4rem;color:#000;margin-top:50px>Поздрави,<p style=font-size:1.4rem;color:#000>Екипът на PHOTONIC</div><div id=container-main-footer style=margin-top:100px><div id=container-main-footer-text style=\"margin:0 auto;background-color:#eaa636;padding:5px 0\"><h4 style=text-align:center;color:#000><a href=http://www.flash-studio.co style=text-decoration:none;color:#000>PHOTONIC</a> © {DateTime.Now.Year}</h4></div></div></div></div>";
        }

        public static string DeclinePhotoShootTemplate(Guid photoshootId)
        {
            return "<!doctypehtml><style>@media only screen and (max-width:600px){.container{width:100%!important}.responsive-img{width:100%!important;height:auto!important}}</style><body style=margin:0;padding:0><table border=0 cellpadding=0 cellspacing=0 width=100%><tr><td style=padding:20px align=center bgcolor=#f0f0f0><table border=0 cellpadding=0 cellspacing=0 width=600 class=container style=background-color:#fff><tr><td style=padding:20px;text-align:center><img src=https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic.png style=display: block; background: rgba(55, 128, 73, .2); color:#378049;width:5%;margin:0 auto;padding:10px;text-align:center;border-radius:10px><h1 style=color:#333;font-family:Arial,sans-serif>Жалко...</h1><h2 style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Отхвърлена заявка за фотосесия.</h2><p style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Можете да следите резервациите си във Вашия профил</p>" + $"<a href='http://www.flash-studio.co/photoshoot/photoshootbyid/{photoshootId}'" + "style=display:inline-block;padding:10px 20px;color:#fff;background-color:#007bff;text-decoration:none;font-family:Arial,sans-serif;font-size:14px;border-radius:5px>Можете да прегледате кадрите от фотосесията тук</a><div class=footer-wrap style=margin-top:60px;width:100%;background:#585858;color:#fff;padding:1px 0><footer style=text-align:center><h4>DREAMPIX © 2024</h4></footer></div><div class=footer-links-wrap style=width:100%;text-align:center;margin-top:10px><a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>DREAMPIX.COM</a> <a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>@dreampix</a></div></table></table>";
        }

        public static string CancelPhotoShootTemplate(Guid photoshootId)
        {
            return "<!doctypehtml><style>@media only screen and (max-width:600px){.container{width:100%!important}.responsive-img{width:100%!important;height:auto!important}}</style><body style=margin:0;padding:0><table border=0 cellpadding=0 cellspacing=0 width=100%><tr><td style=padding:20px align=center bgcolor=#f0f0f0><table border=0 cellpadding=0 cellspacing=0 width=600 class=container style=background-color:#fff><tr><td style=padding:20px;text-align:center><img src=https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic.png style=display: block; background: rgba(55, 128, 73, .2); color:#378049;width:5%;margin:0 auto;padding:10px;text-align:center;border-radius:10px><h1 style=color:#333;font-family:Arial,sans-serif>Жалко...</h1><h2 style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Отказана заявка за фотосесия.</h2><p style=color:#666;font-family:Arial,sans-serif;font-size:14px;line-height:1.5>Можете да следите резервациите си във Вашия профил</p>" + $"<a href='http://www.flash-studio.co/photoshoot/photoshootbyid/{photoshootId}'" + "style=display:inline-block;padding:10px 20px;color:#fff;background-color:#007bff;text-decoration:none;font-family:Arial,sans-serif;font-size:14px;border-radius:5px>Можете да прегледате кадрите от фотосесията тук</a><div class=footer-wrap style=margin-top:60px;width:100%;background:#585858;color:#fff;padding:1px 0><footer style=text-align:center><h4>DREAMPIX © 2024</h4></footer></div><div class=footer-links-wrap style=width:100%;text-align:center;margin-top:10px><a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>DREAMPIX.COM</a> <a href=http://www.flash-studio.co style=width:400px;color:#424242;margin-left:20px;font-size:.9rem>@dreampix</a></div></table></table>";
        }
    }
}
