using OwlStock.Domain.Enumerations;

namespace OwlStock.Infrastructure.Common.EmailTemplates.PhotoShoot
{
    public static class PhotoShootEmailTemplates
    {
        public static string CreatePhotoShootTemplate(DateTime date, PhotoShootType photoshootType, Guid photoshootId)
        {
            return $"<!doctypehtml><html lang=en><meta charset=UTF-8><meta content=\"width=device-width,initial-scale=1\"name=viewport><title>Резервацията беше направена успешно!</title><body style=font-family:Verdana,Geneva,Tahoma,sans-serif><div id=container style=width:100%><div style=\"width:100%;margin:0 auto\"class=container-main><div id=container-main-header><div id=container-main-header-logo style=width:100%;text-align:center><img src=https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic_UPPER_dark.png style=width:50%></div></div><div id=container-main-title style=\"width:100%;margin:100px 0\"><h2 style=text-align:center;color:#000>Фотосесията е резервирана <span style=color:#eaa636>успешно</span>!</h2></div><hr><div id=container-main-table-details style=width:100%;font-size:1.2rem><table style=\"width:100%;margin:20px 0\"><tr><td><b>Фотосесия</b><td>{photoshootType}<tr><td style=text-align:left><b>Дата</b><td style=text-align:left>{date}</table></div><hr><div id=container-main-text style=margin-top:40px><p style=color:#000>Резервацията ще бъде прегледана и ще получите обаждане от нас в най-скоро време. Повече информация може да откриете <a href=http://www.flash-studio.co/Photoshoot/PhotoshootById/{photoshootId} style=text-decoration:none;color:#eaa636><b>тук</b></a>.<p style=color:#000;margin-top:40px;color:#000>Благодарим Ви, че изплозвате нашите услуги!<p style=color:#000;margin-top:40px>Поздрави,<p style=color:#000>Екипът на PHOTONIC</div><div id=container-main-footer style=margin-top:50px><div id=container-main-footer-text style=\"margin:0 auto;background-color:#eaa636;padding:5px 0\"><h4 style=text-align:center;color:#000><a href=http://www.flash-studio.co style=text-decoration:none;color:#000>PHOTONIC</a> © {DateTime.Now.Year}</h4></div></div></div></div>";
        }

        public static string CreatePhotoShootTemplateDreampix(DateTime date, PhotoShootType photoshootType)
        {
            return $"<div class=\"container\"> <div class=\"content\"> <h2 class=\"username\">Здравей,</h2> <br> <h1 class=\"text\">Направена е нова рервация.</i></h1> <hr> <div class=\"details\"> <table> <tbody> <tr> <td>Date:</td> <td><i>{date.ToShortDateString()}</i></td> </tr> <tr> <td>Type:</td> <td><i>{photoshootType}</i></td> </tr> </tbody> </table> </div> <hr> <div class=\"greetings\"</div> <hr> <div class=\"footer\"> <h1>OwlStock</h1> <br> <h4>2023</h4> </div> </div> </div> <style> *{{margin: 0;padding: 5px 8px;}}hr{{margin: 10px 10px;padding: 0;}}.container{{font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;width: 100%;text-align: center;}}.container .content{{width: 100%;margin: 0 auto;padding: 20px 0;background-color: #EBEAE1;}}.container .content .details table{{margin: 0 auto;}}.container .content .greetings h2{{margin-top: 20px;}}</style> ";
        }

        public static string UpdatePhotoShootTemplate(Guid photoshootId)
        {
            return $"<!doctypehtml><html lang=en><meta charset=UTF-8><meta content=\"width=device-width,initial-scale=1\"name=viewport><title>Страхотни новини!</title><body style=font-family:Verdana,Geneva,Tahoma,sans-serif><div id=container style=width:100%><div style=\"width:100%;margin:0 auto\"class=container-main><div id=container-main-header><div id=container-main-header-logo style=width:100%;text-align:center><img src=https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic_UPPER_dark.png style=width:50%></div></div><div id=container-main-title style=\"width:100%;margin:60px 0\"><h2 style=text-align:center;color:#000>Снимките от Вашата фотосесия са <span style=color:#eaa636>готови</span>!</h2></div><div id=container-main-text style=margin-top:50px><p>Всички снимки от Вашата фотосесия са налични в профила Ви. Може да ги прегледате или изтеглите от Вашата лична галерия.<p style=margin-top:40px><a href=http://www.flash-studio.co/Photoshoot/PhotoshootById/{photoshootId} style=\"background:#eaa636;padding:10px 30px;text-decoration:none;color:#000\"><b>Моята галерия</b></a><p style=margin-top:40px;color:#000>Благодарим Ви, че изплозвате нашите услуги!<p style=color:#000;margin-top:40px>Поздрави,<p style=color:#000>Екипът на PHOTONIC</div><div id=container-main-footer style=margin-top:50px><div id=container-main-footer-text style=\"margin:0 auto;background-color:#eaa636;padding:5px 0\"><h4 style=text-align:center;color:#000><a href=http://www.flash-studio.co style=text-decoration:none;color:#000>PHOTONIC</a> © {DateTime.Now.Year}</h4></div></div></div></div>";
        }

        public static string UpdatePhotoShootDataTemplate(Guid photoshootId, PhotoShootType photoshootType, string photoshootNumber, DateTime date)
        {
            return $"<!doctypehtml><html lang=en><meta charset=UTF-8><meta content=\"width=device-width,initial-scale=1\"name=viewport><title>Актуализирана фотосесия</title><body style=font-family:Verdana,Geneva,Tahoma,sans-serif><div id=container style=width:100%><div style=\"width:100%;margin:0 auto\"class=container-main><div id=container-main-header><div id=container-main-header-logo style=width:100%;text-align:center><img src=https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic_UPPER_dark.png style=width:50%></div></div><div id=container-main-title style=\"width:100%;margin:40px 0\"><h2 style=text-align:center;color:#000>Данните за фотосесия №{photoshootNumber} бяха актуализирани <span style=color:#eaa636>успешно</span>!</h2></div><hr><div id=container-main-table-details style=width:100%;font-size:1.2rem><table style=\"width:100%;margin:20px 0\"><tr><td><b>Фотосесия</b><td>{photoshootType}<tr><td style=text-align:left><b>Дата</b><td style=text-align:left>{date}</table></div><hr><div id=container-main-text style=margin-top:40px><p style=color:#000>Повече информация може да откриете <a href=http://www.flash-studio.co/Photoshoot/PhotoshootById/{photoshootId} style=text-decoration:none;color:#eaa636><b>тук</b></a>.<p style=margin-top:40px;color:#000>Благодарим Ви, че изплозвате нашите услуги!<p style=color:#000;margin-top:40px>Поздрави,<p style=color:#000>Екипът на PHOTONIC</div><div id=container-main-footer style=margin-top:50px><div id=container-main-footer-text style=\"margin:0 auto;background-color:#eaa636;padding:5px 0\"><h4 style=text-align:center;color:#000><a href=http://www.flash-studio.co style=text-decoration:none;color:#000>PHOTONIC</a> © {DateTime.Now.Year}</h4></div></div></div></div>";
        }

        public static string DeclinePhotoShootTemplate(Guid photoshootId)
        {
            return $"<!doctypehtml><html lang=\"en\"><meta charset=\"UTF-8\"><meta content=\"width=device-width,initial-scale=1\"name=\"viewport\"><title>Отказана фотосесия</title><body style=\"font-family:Verdana,Geneva,Tahoma,sans-serif\"><div id=\"container\"style=\"width:100%\"><div style=\"width:100%;margin:0 auto\"class=\"container-main\"><div id=\"container-main-header\"><div id=\"container-main-header-logo\"style=\"width:100%;text-align:center\"><img src=\"https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic_UPPER_dark.png\"style=\"width:50%\"></div></div><div id=\"container-main-title\"style=\"width:100%;margin-top:100px\"><h2 style=\"text-align:center;color:#000\">Отказана фотосесия</h2></div><div id=\"container-main-text\"style=\"margin-top:60px\"><p style=\"color:#000\">Здравейте,<p style=\"color:#000\">Благодарим Ви за направената резервация! За съжаление, поради независещи от нас обстоятелства, на избраната от Вас дата няма да бъде възможно да проведем фотосесията.<p style=\"color:#000;margin-top:40px\">Може да направите нова резервация, като изберете друга дата и час през нашата онлайн форма за резервация.<p style=\"margin-top:40px\"><a href=\"http://www.flash-studio.co/PhotoShoot/Reserve\"style=\"text-decoration:none;padding:10px 15px;color:#000;background:#eaa636\"><b>НОВА РЕЗЕРВАЦИЯ</b></a><p style=\"color:#000;margin-top:40px\">Искрено се извиняваме за причиненото неудобство!<p style=\"margin-top:40px\"><a href=\"http://flash-studio.co/Photoshoot/PhotoshootById/{photoshootId}\"style=\"text-decoration:none;padding:10px 15px;color:#000;background:#eaa636\"><b>ПРЕГЛЕД НА ЗАЯВКАТА</b></a><p style=\"color:#000;margin-top:40px\">Благодарим Ви, че изплозвате нашите услуги!<p style=\"color:#000;margin-top:40px\">С уважение,<p style=\"color:#000\">Екипът на PHOTONIC</div><div id=\"container-main-footer\"style=\"margin-top:50px\"><div id=\"container-main-footer-text\"style=\"margin:0 auto;background-color:#eaa636;padding:5px 0\"><h4 style=\"text-align:center;color:#000\"><a href=\"http://www.flash-studio.co\"style=\"text-decoration:none;color:#000\">PHOTONIC</a> © {DateTime.Now.Year}</h4></div></div></div></div>";
        }

        public static string CancelPhotoShootTemplate(Guid photoshootId)
        {
            return $"<!doctypehtml><html lang=\"en\"><meta charset=\"UTF-8\"><meta content=\"width=device-width,initial-scale=1\"name=\"viewport\"><title>Отменена фотосесия</title><body style=\"font-family:Verdana,Geneva,Tahoma,sans-serif\"><div id=\"container\"style=\"width:100%\"><div style=\"width:100%;margin:0 auto\"class=\"container-main\"><div id=\"container-main-header\"><div id=\"container-main-header-logo\"style=\"width:100%;text-align:center\"><img src=\"https://raw.githubusercontent.com/xnikoloff/OwlStock/refs/heads/develop/OwlStock.Web/wwwroot/photonic_UPPER_dark.png\"style=\"width:50%\"></div></div><div id=\"container-main-title\"style=\"width:100%;margin-top:100px\"><h2 style=\"text-align:center;color:#000\">Отменена фотосесия</h2></div><div id=\"container-main-text\"style=\"margin-top:60px\"><p style=\"color:#000\">Здравейте,<p style=\"color:#000\">Вашата резервация за фотосесия беше отменена.<p style=\"color:#000;margin-top:40px\">Ще се радваме да раборим заедно отново в бъдеще! Може да направите нова резервация от тук:<p style=\"margin-top:40px\"><a href=\"http://www.flash-studio.co/PhotoShoot/Reserve\"style=\"text-decoration:none;padding:10px 15px;color:#000;background:#eaa636\"><b>НОВА РЕЗЕРВАЦИЯ</b></a><p style=\"color:#000;margin-top:40px\">Благодарим Ви, че изплозвате нашите услуги!<p style=\"color:#000;margin-top:40px\">С уважение,<p style=\"color:#000\">Екипът на PHOTONIC</div><div id=\"container-main-footer\"style=\"margin-top:50px\"><div id=\"container-main-footer-text\"style=\"margin:0 auto;background-color:#eaa636;padding:5px 0\"><h4 style=\"text-align:center;color:#000\"><a href=\"http://www.flash-studio.co\"style=\"text-decoration:none;color:#000\">PHOTONIC</a> © {DateTime.Now.Year}</h4></div></div></div></div>";
        }
    }
}
